<?php

namespace Scavenger\WebserviceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BattlezoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattlezoneRepository extends EntityRepository
{
}