<?php

namespace Scavenger\WebserviceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLocationRepository extends EntityRepository
{
}